-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here

-- Mapping for bufferline go_to function
-- local function setBufferlineKey(key, buf_index)
--   vim.keymap.set("n", "<Space>" .. key, function()
--     require("barbar").go_to(buf_index, true)
--   end, { silent = true, desc = "Tab " .. buf_index })
-- end
--
-- -- Set mappings for each tab
-- setBufferlineKey("1", 1)
-- setBufferlineKey("2", 2)
-- setBufferlineKey("3", 3)
-- setBufferlineKey("4", 4)
-- setBufferlineKey("5", 5)
-- setBufferlineKey("6", 6)
-- setBufferlineKey("7", 7)
-- setBufferlineKey("8", 8)
-- setBufferlineKey("9", 9)
--
-- -- Mapping for switching between last two tabs
-- vim.keymap.set("n", "`", ":e #<CR>", { silent = true, desc = "Switch Tab" })
--
-- -- Mapping for switching between last two tabs
-- vim.keymap.set("n", "`", ":e #<CR>", { silent = true, desc = "Switch Tab" })
